### ISSUE TITLE
VNS deal gets rejected 

### ISSUE THREAD

**Issue by karin100** [OpenGamma/Strata#1379]
I have a vns trade with 1M tenor, and step periods are at the end of each month.
Im getting an error : "ValueStep date does not match a period boundary" for the step "2021-03-31" because the termination date is set to "2022-09-30" 

[VNS_LCH_NoStub.txt](https://github.com/OpenGamma/Strata/files/518266/VNS_LCH_NoStub.txt)

**Comment by jodastephen** [comment]
See https://github.com/OpenGamma/Strata/issues/1354 fixed in v1.1. Summary, this FpML is dubious as the effective start date is not on the last day of the month (its the last business day). Strata v1.1 has been changed to handle this last business day case (I haven't tried this specific example, but it should work with v1.1)
