### ISSUE TITLE
add the "holiday calendar" for "Germany"

### ISSUE THREAD

**Issue by nimo23** [OpenGamma/Strata#1518]
Please add the "holiday calendar" for **Berlin, Germany** in GlobalHolidayCalendars:

`public static final HolidayCalendar BERL = generateBerlin();`

Thanks.

**Comment by jodastephen** [comment]
We use the [codes from FpML](http://www.fpml.org/coding-scheme/business-center-7-22.xml). The German codes are:

* DECO - Cologne, Germany
* DEDU - Dusseldorf, Germany
* DEFR - Frankfurt, Germany
* DELE - Leipzig, Germany
* DEMA - Mainz, Germany
* DEMU - Munich, Germany
* DEST - Stuttgart, Germany

There is no code for Berlin.

We don't currently have any of the German codes (because German financial instruments usually use the EU TARGET calendar).

This is the [code necessary](https://github.com/OpenGamma/Strata/commit/0060737145c3f8da87d642eaf9edaae718b25030#diff-d279109d91d43a232be73522d1cefd0e) to add a holiday calendar (the commit also includes adding an index). The main thing is researching the holiday dates from original sources (and a variety of them). If you're interested, a PR for DEFR would be considered.

**Comment by nimo23** [comment]
Okay, thanks. I understand.

So when using "HolidayCalendarIds.EUTA" then actually not all "public holidays" of **Germany** are considered. For example, in germany, yesterday was a public holiday. 

So we need "HolidayCalendarIds.DEFR" to treat german public holidays. I will try to make a "HolidayCalendarIds.DEFR".

**Comment by nimo23** [comment]
Okay, I added:

https://github.com/OpenGamma/Strata/pull/1520
https://github.com/OpenGamma/Strata/pull/1521

Please, feel free to close this issue after successfully commiting my pull requests. 

Thanks.

**Comment by jodastephen** [comment]
Fixed by #1560
