### ISSUE TITLE
CSV parsing - whitespace not trimmed if field is quoted

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1933]
A field in a CSV file containing a single space is trimmed and `Optional.empty()` is returned from`CsvRow.findField()`.

If a field contains a single space surrounded by quotes then the field value is a single space.

The presence of quotes is normally completely transparent to the consumer of the field data.
In this case it isn't. `findField()` returns `Optional.empty()` if there are no quotes and `Optional.of(" ")` if there are.

**Comment by headphonejack** [comment]
Isn't `" "` different from ` ` in a CSV file? That is to say, a CSV cell entry should contain all its contents between two commas, so

**Comment by cjkent** [comment]
The quotes aren't part of the value. The value returned from the parser doesn't include the quotes. They're a detail of the encoding, not the data.

**Comment by cjkent** [comment]
The current behaviour seems incorrect as the caller shouldn't have to care about the presence of quotes. But fixing this issue would remove the ability to parse untrimmed data out of a CSV file.

Preserving whitespace seems like an edge case. Maybe the best fix would be to trim by default even in the presence of quotes, but to provide an additional option to preserve whitespace.

This would ensure the presence of quotes is transparent to the caller but would allow whitespace to be encoded when necessary.

**Comment by jodastephen** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Comma-separated_values) references the RFC which says that "Spaces are considered part of a field and should not be ignored". We do ignore them when not quoted, but don't when they are quoted (which seems reasonable and I suspect is quite common). As such, I think the current behaviour is correct (although the Javadoc could do with work).

I suspect it would be OK to change the behaviour (as the current Javadoc promises the data is trimmed). There should be additional methods `CsvRow.getUntrimmed()` (ie. trimming just before returning in the other methods, rather than trimming when parsing).

**Comment by cjkent** [comment]
>I suspect it would be OK to change the behaviour (as the current Javadoc promises the data is trimmed). There should be additional methods CsvRow.getUntrimmed() (ie. trimming just before returning in the other methods, rather than trimming when parsing).

I think that seems like a sensible approach.

**Comment by jodastephen** [comment]
On looking into it, a quoted space does have meaning, so I've just updated the docs and fixed a related problem with empty lines,
