### ISSUE TITLE
Failing to build on both Ubuntu 19.04 or Fedora 30 using default apt and yum Maven/JVM

### ISSUE THREAD

**Issue by vegabook** [OpenGamma/Strata#1973]
Having failed to build on Jetson, I've tried on both Fedora 30 and Ubuntu 19.04 on an x86-compatible AMD Ryzen 2700x with 64GB RAM. I'm doing README.md's simple instructions: cloning the repo, `cd Strata`, then `mvn install`. Herewith the ascii casts (you can scroll to the end to see the errors). The casts include kernel versions and Maven and Java versions.

Fedora:
https://asciinema.org/a/sMFOwZS2h0qPvR8cgBefeUkRI

Ubuntu:
https://asciinema.org/a/yFljdO7oiz1TnVOg42wHJhycp

In both cases I'm installing default repo maven via `sudo apt install maven` and `sudo yum install maven` in Ubuntu and Fedora respectively. 

So essentially, latest builds of these two OSs, with default JVM and Maven, fail to build the repo.  Also fails to build with similar error on LTS Ubuntu 18.04.

**Comment by jodastephen** [comment]
The problem is with JavaFX. Versions of Java from OpenJDK providers often don't have JavaFX included.

If you run with OpenJDK 11 instead of OpenJDK 8, the Strata build will include the JavaFX jar file from Maven Central and work fine. But on Java 8 that approach is not available. As such, on Java 8 the only real solution is to use a JDK that includes JavaFX.

**Comment by vegabook** [comment]
Yeah got it working, on both 18,04 LTS and 19.04.

Had to install openjdk-11-jdk
`sudo apt install openjdk-11-jdk`

![image](https://user-images.githubusercontent.com/3780883/58128166-e717e500-7c0e-11e9-995b-d3b258dde142.png)

**Comment by vegabook** [comment]
Is it worth putting what you said about openjdk-11 into the readme.md? Happy to do it if you want...
