### ISSUE TITLE
Inflation swap functions and examples

### ISSUE THREAD

**Issue by jonathansenior** [OpenGamma/Strata#600]

**Comment by fmovlex** [comment]
Is this included in 0.9.0/planned soon? Couldn't find an inflation swap example

**Comment by jodastephen** [comment]
The examples are not done yet, however the actual swap pricer is done. It works just like normal swap pricing, except that you use `InflationRateCalculation` instead of `IborRateCalculation`.

**Comment by fmovlex** [comment]
Yeah, the issue was mainly with the curve parsing - the inflation curve is expected to be `Months`/`PriceIndex` (`ForwardPriceIndexValues` ctor), unlike normal swaps which is `YearFraction` (hard-coded) / `ZeroRate`.
Also, a fixing time-series seems to be required (why?)
It's working though, thanks.

**Comment by jodastephen** [comment]
Looks like we need to provide a way to create a `ForwardPriceIndexValues` without a time-series.

**Comment by jodastephen** [comment]
The inflation code has been reworked to handle seasonality properly. The measures are the normal measures for swaps.
