### ISSUE TITLE
Expose CurveSettings

### ISSUE THREAD

**Issue by fmovlex** [OpenGamma/Strata#739]
Hey, I'd open a small pull request but I guess this is relevant to more than one loader and I'm not sure how you'd handle that.

Specifically, in `RatesCurvesCsvLoader` - consider a case where the user uses Strata's format for `groups.csv` and `settings.csv`, but supplies his own csv/xml/whatever for the curve data itself (meaning - implement loadSingle themselves) .

Groups can be loaded via `CurveGroupDefinitionCsvLoader.loadCurveGroups`,
but `RatesCurvesCsvLoader.loadCurveSettings` is protected (and the class `LoadedCurveSettings` is itself protected).

Perhaps I'm looking at this the wrong way, but I assume this scenario of external curve data is pretty common (?). Thanks guys.

**Comment by jodastephen** [comment]
The `RatesCurvesCsvLoader` class was designed with the primary focus of being the loader for the Strata CSV file format. Consideration of allowing for other CSV formats (or XML etc) did not take place. This is because it is possible to load those files in your own code and just create the relevant curve objects directly. The groups loader was made public because it shares code within Strata, rather than with the intention of it being widely used in application code.

What we do want to do is create a wider pluggable "framework" for loading data, such as market and reference data. It is perhaps this that you need. The code would involve a means whereby a loader could examine a directory or file and load an entire set of market data from it, with different pluggable loaders for individual CSV/XML/other file formats.

As such, I'm slightly reluctant to make `LoadedCurveSettings` and the settings loader public, although I can see how it might help.

Does that help with understanding our thoughts? We also have [forums](http://forums.opengamma.com/) for discussion of Strata.

**Comment by fmovlex** [comment]
Yeah, a framework like that is what I (and I assume others) will use. 
I guess I viewed `groups.csv` and `settings.csv` differently than what was intended - I used them independently to define my data, then planned to load something like `curves.csv` in-memory (there is no file, which mean I would need a resourceLocator with a byte[] bytestream).

It obviously involves a bit more code to create the curve objects myself, but I guess it'll work itself out once I get in there. Thanks jodastephen
